export const SET_SUB_HEADER = "SET_SUB_HEADER";
export const SET_ACTIVE_TRACKER_ITEM = "SET_ACTIVE_TRACKER_ITEM";

export const FETCH_SUCCESSFUL="FETCH_SUCCESSFUL";
export const FETCH_FAILED="FETCH_FAILED";

export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE";
