export const FETCH_PORTFOLIO_RISK_SUCCESS = "FETCH_PORTFOLIO_RISK_SUCCESS";
export const FETCH_PORTFOLIO_RISK_FAILURE = "FETCH_PORTFOLIO_RISK_FAILURE";

export const SAVE_PORTFOLIO_RISK_SUCCESS = "SAVE_PORTFOLIO_RISK_SUCCESS";
export const SAVE_PORTFOLIO_RISK_FAILURE = "SAVE_PORTFOLIO_RISK_FAILURE";
